version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
          - 'eslint-plugin-astro'
          - 'prettier-plugin-astro'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'
